site_name: Credit Risk Calculator
site_url: https://example.com/docs
repo_url: https://github.com/yourorg/credit_risk_calculator
repo_name: GitHub
nav:
  - Home: index.md
  - Architecture: architecture.md
  - API Reference: api.md
  - ADRs:
      - "ADR 0001": adr/0001-record-architecture-decision.md
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
markdown_extensions:
  - admonition
  - toc:
      permalink: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys, os; sys.path.append(os.path.abspath("src")) 